basePath: /api/v1
host: localhost:8090
info:
  contact: {}
  description: Maily backend server
  title: Maily API
  version: "1.0"
paths:
  /example/12345:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: "1234"
      tags:
      - example
swagger: "2.0"
