# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Set environment variables
      env:
        DB_HOST: $DB_HOST
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
        DB_PORT: $DB_PORT
        DB_DATABASE: $DB_DATABASE
        IP_ADDRESS_API_KEY: $IP_ADDRESS_API_KEY
        API_SECRET: $API_SECRET
        TOKEN_HOUR_LIFESPAN: $TOKEN_HOUR_LIFESPAN
        TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
        
    - name: Build project
      run: |
        go build -tags netgo -ldflags '-s -w' -o app

    - name: Run project
      run: |
        nohup ./app &
